scrape_configs:
  - job_name: "prometheus"
    static_configs: [{ targets: ["prometheus:9090"] }]
  - job_name: "node"
    static_configs: [{ targets: ["node_exporter:9100"] }]
  - job_name: "mysql"
    static_configs: [{ targets: ["mysqld_exporter:9104"] }]
  - job_name: "custom"
    static_configs:
        - targets: ['host.docker.internal:8000']

